http_server_host = "${HTTP_SERVER_HOST}"
http_server_port = ${HTTP_SERVER_PORT}
ipfs_seed = ${IPFS_SEED}
ipfs_port = ${IPFS_PORT}
ipfs_path = "${IPFS_PATH}"
full_node_rpc = ${FULL_NODE_RPC}
full_node_ws = ${FULL_NODE_WS}
app_id = ${APP_ID}
confidence = ${CONFIDENCE}
avail_path = "${AVAIL_PATH}"
bootstraps = ${BOOTSTRAPS}
